In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandasql import sqldf

print("Всё работает")

Всё работает

In [3]:
orders = pd.read_csv('/home/art/olist_data/olist_orders_dataset.csv')

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
sqldf("SELECT * FROM orders LIMIT 5")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
sqldf("SELECT order_id, customer_id, order_status FROM orders LIMIT 10")

,order_id,customer_id,order_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered

In [6]:
sqldf("SELECT * FROM orders WHERE order_status = 'delivered' LIMIT 10")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
7,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
8,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
9,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00

In [7]:
sqldf("SELECT order_id, order_purchase_timestamp, order_status FROM orders ORDER BY order_purchase_timestamp LIMIT 10 ")

                           order_id order_purchase_timestamp order_status
0  2e7a8482f6fb09756ca50c10d7bfc047      2016-09-04 21:15:19      shipped
1  e5fa5a7210941f7d56d0208e4e071d35      2016-09-05 00:15:34     canceled
2  809a282bbd5dbcabb6f2f724fca862ec      2016-09-13 15:24:19     canceled
3  bfbd0f9bdef84302105ad712db648a6c      2016-09-15 12:16:38    delivered
4  71303d7e93b399f5bcd537d124c0bcfa      2016-10-02 22:07:52     canceled
5  3b697a20d9e427646d92567910af6d57      2016-10-03 09:44:50    delivered
6  be5bc2f0da14d8071e2d45451ad119d9      2016-10-03 16:56:50    delivered
7  65d1e226dfaeb8cdc42f665422522d14      2016-10-03 21:01:41     canceled
8  a41c8759fbe7aab36ea07e038b2d4465      2016-10-03 21:13:36    delivered
9  d207cc272675637bfed0062edffd0818      2016-10-03 22:06:03    delivered

In [8]:
sqldf("SELECT order_id, order_purchase_timestamp, order_status FROM orders ORDER BY order_purchase_timestamp DESC LIMIT 10 ")

                           order_id order_purchase_timestamp order_status
0  10a045cdf6a5650c21e9cfeb60384c16      2018-10-17 17:30:18     canceled
1  b059ee4de278302d550a3035c4cdb740      2018-10-16 20:16:02     canceled
2  a2ac6dad85cf8af5b0afb510a240fe8c      2018-10-03 18:55:29     canceled
3  616fa7d4871b87832197b2a137a115d2      2018-10-01 15:30:09     canceled
4  392ed9afd714e3c74767d0c4d3e3f477      2018-09-29 09:13:03     canceled
5  869997fbe01f39d184956b5c6bccfdbe      2018-09-26 08:40:15     canceled
6  5aac76cf7b07dd06fa4d50bf461d2f40      2018-09-25 11:59:18     canceled
7  ed3efbd3a87bea76c2812c66a0b32219      2018-09-20 13:54:16     canceled
8  bd35b677fd239386e9861d11ae98ab56      2018-09-17 17:21:16     canceled
9  ea844c92cf978ea23321fa7fe5871761      2018-09-13 09:56:12     canceled

In [9]:
sqldf("SELECT order_status, COUNT(*) AS count FROM orders GROUP BY order_status ORDER BY count DESC")

  order_status  count
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7     approved      2

In [10]:
sqldf("""
    SELECT 
        order_status,
        COUNT(*) AS count, 
        MIN(order_purchase_timestamp) AS first_order, 
        MAX(order_purchase_timestamp) AS last_order
    FROM orders
    GROUP BY order_status
    ORDER BY count DESC
""")

  order_status  count          first_order           last_order
0    delivered  96478  2016-09-15 12:16:38  2018-08-29 15:00:37
1      shipped   1107  2016-09-04 21:15:19  2018-09-03 09:06:57
2     canceled    625  2016-09-05 00:15:34  2018-10-17 17:30:18
3  unavailable    609  2016-10-05 14:16:28  2018-08-21 12:21:00
4     invoiced    314  2016-10-04 13:02:10  2018-08-14 18:45:08
5   processing    301  2016-10-05 22:44:13  2018-07-23 18:03:03
6      created      5  2017-11-06 13:12:34  2018-02-09 17:21:04
7     approved      2  2017-02-06 20:18:17  2017-04-25 01:25:34

In [11]:
sqldf("""
    SELECT order_status, COUNT(*) AS count
    FROM orders
    GROUP BY order_status
    HAVING COUNT(*) > 1000
""")

  order_status  count
0    delivered  96478
1      shipped   1107

In [12]:
sqldf("""
    SELECT order_status, COUNT(*) AS count
    FROM orders
    WHERE order_purchase_timestamp >= '2018-01-01'
    GROUP BY order_status
    HAVING COUNT(*) > 100
    ORDER BY count DESC
""")

  order_status  count
0    delivered  52783
1      shipped    568
2     canceled    334
3  unavailable    145
4     invoiced    121

In [13]:
order_items = pd.read_csv('/home/art/olist_data/olist_order_items_dataset.csv')
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [14]:
sqldf("SELECT SUM(price) AS total_revenue FROM order_items")

   total_revenue
0     13591643.7

In [15]:
sqldf("SELECT AVG(price) AS avg_price FROM order_items")

    avg_price
0  120.653739

In [16]:
sqldf("SELECT MIN(price) AS min_price, MAX(price) AS max_price FROM order_items")

   min_price  max_price
0       0.85     6735.0

In [17]:
sqldf("SELECT COUNT(DISTINCT order_id) AS unique_orders FROM order_items")

   unique_orders
0          98666

In [18]:
sqldf("""
    SELECT
        order_id,
        COUNT(*) AS items_count,
        SUM(price) AS order_total,
        AVG(price) AS avg_item_price
    FROM order_items
    GROUP BY order_id
    LIMIT 10
""")

                           order_id  items_count  order_total  avg_item_price
0  00010242fe8c5a6d1ba2dd792cb16214            1        58.90           58.90
1  00018f77f2f0320c557190d7a144bdd3            1       239.90          239.90
2  000229ec398224ef6ca0657da4fc703e            1       199.00          199.00
3  00024acbcdf0a6daa1e931b038114c75            1        12.99           12.99
4  00042b26cf59d7ce69dfabb4e55b4fd9            1       199.90          199.90
5  00048cc3ae777c65dbb7d2a0634bc1ea            1        21.90           21.90
6  00054e8431b9d7675808bcb819fb4a32            1        19.90           19.90
7  000576fe39319847cbb9d288c5617fa6            1       810.00          810.00
8  0005a1a1728c9d785b8e2b08b904576c            1       145.95          145.95
9  0005f50442cb953dcd1d21e1fb923495            1        53.99           53.99

In [19]:
sqldf("SELECT COUNT(*) FROM orders")

   COUNT(*)
0     99441

In [20]:
sqldf("SELECT COUNT(*) AS count FROM orders WHERE order_status = 'delivered'")

   count
0  96478

In [21]:
sqldf("SELECT COUNT(DISTINCT customer_id) AS unique_customers FROM orders")

   unique_customers
0             99441

In [22]:
sqldf("SELECT order_status, COUNT(*) AS count FROM orders GROUP BY order_status ORDER BY count DESC LIMIT 5")

  order_status  count
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314

In [23]:
sqldf("SELECT COUNT(*) AS count_orders_in_2018 FROM orders WHERE order_purchase_timestamp >= '2018-01-01' AND order_purchase_timestamp < '2019-01-01'")

   count_orders_in_2018
0                 54011

In [24]:
customers = pd.read_csv('/home/art/olist_data/olist_customers_dataset.csv')
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [26]:
customers.shape

(99441, 5)

In [27]:
sqldf("""
    SELECT
        orders.order_id,
        orders.order_status,
        customers.customer_city,
        customers.customer_state
    FROM orders
    JOIN customers ON orders.customer_id = customers.customer_id
    LIMIT 10
""")

,order_id,order_status,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,santo andre,SP
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,congonhinhas,PR
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,santa rosa,RS
7,6514b8ad8028c9f2cc2374ded245783f,delivered,nilopolis,RJ
8,76c6e866289321a7c93b82b54852dc33,delivered,faxinalzinho,RS
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,sorocaba,SP

In [29]:
sqldf("""
    SELECT
        orders.order_id,
        customers.customer_city,
        order_items.price,
        order_items.freight_value
    FROM orders
    JOIN customers ON orders.customer_id = customers.customer_id
    JOIN order_items ON orders.order_id = order_items.order_id
    LIMIT 10
""")

,order_id,customer_city,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,sao paulo,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,barreiras,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,vianopolis,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,sao goncalo do amarante,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,santo andre,19.90,8.72
5,a4591c265e18cb1dcee52889e2d8acc3,congonhinhas,147.90,27.36
6,136cce7faa42fdb2cefd53fdc79a6098,santa rosa,49.90,16.05
7,6514b8ad8028c9f2cc2374ded245783f,nilopolis,59.99,15.17
8,76c6e866289321a7c93b82b54852dc33,faxinalzinho,19.90,16.05
9,e69bfb5eb88e0ed6a785585b27e16dbf,sorocaba,149.99,19.77